// Centralized auto-title for simplified expenses (Part 4). The manager never
// types a title; it is derived from the active category name + a safe summary of
// the plain-text shopping list. Regenerate on category/list change before final
// verification; the stored value is preserved for historical display.
// NOT generated by AI.

const MAX_SUMMARY = 60;
const MAX_TITLE = 120;

/** Collapse whitespace/newlines and strip angle brackets (defensive vs. HTML). */
function sanitize(s: string): string {
  return s.replace(/[<>]/g, " ").replace(/\s+/g, " ").trim();
}

/**
 * "Категория: краткое содержание списка". Uses the first meaningful line of the
 * shopping list, safely truncated. Falls back to the category name alone when
 * the list is empty. Always concise + injection-safe (no HTML/script).
 */
export function buildExpenseTitle(categoryName: string, shoppingListText: string | null | undefined): string {
  const cat = sanitize(categoryName || "Расход");
  const firstLine = sanitize((shoppingListText ?? "").split(/\r?\n/).find((l) => sanitize(l).length > 0) ?? "");
  if (!firstLine) return cat.slice(0, MAX_TITLE);
  const summary = firstLine.length > MAX_SUMMARY ? `${firstLine.slice(0, MAX_SUMMARY - 1).trimEnd()}…` : firstLine;
  return `${cat}: ${summary}`.slice(0, MAX_TITLE);
}
