-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "confidence" TEXT NOT NULL DEFAULT 'low',
ADD COLUMN     "counterpartyAccount" TEXT,
ADD COLUMN     "counterpartyBankBik" TEXT,
ADD COLUMN     "counterpartyBankName" TEXT,
ADD COLUMN     "counterpartyCorrAccount" TEXT,
ADD COLUMN     "counterpartyInn" TEXT,
ADD COLUMN     "counterpartyKpp" TEXT,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'RUB',
ADD COLUMN     "expenseCategory" TEXT,
ADD COLUMN     "invoiceNumber" TEXT,
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "originalFileMime" TEXT,
ADD COLUMN     "originalFileName" TEXT,
ADD COLUMN     "originalFileSize" INTEGER,
ADD COLUMN     "originalFileStorageKey" TEXT,
ADD COLUMN     "rawExtractedJson" TEXT,
ALTER COLUMN "counterpartyName" DROP NOT NULL,
ALTER COLUMN "amountKopeks" SET DEFAULT 0,
ALTER COLUMN "subject" DROP NOT NULL,
ALTER COLUMN "invoiceDate" DROP NOT NULL,
ALTER COLUMN "dueDate" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'draft';

